import { Inter } from "next/font/google";
import "./globals.css";

import Navigation from "./components/Navigation";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Soccer Manager",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navigation />
				<div className="pageContainer">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
